[[bin]]
name = "build_benchmark_jsons"
path = "src/build_benchmark_jsons.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }

[package]
description = "Bench tools for WRY"
edition = "2018"
name = "bench_tools"
version = "0.1.0"
